### NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.2'

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## What is Array?

![](image/array.png)

In [4]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [5]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [6]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### Lists

In [7]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])

v

array([1, 2, 3, 4, 5])

In [8]:
# matrix: the argument to the array function is a nested list
m = np.array([
              [1, 2, 3], 
              [4, 5, 6]
            ])

m

array([[1, 2, 3],
       [4, 5, 6]])

The `v` and `m` objects are both of the type `ndarray` that the `numpy` module provides.

In [9]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [10]:
a = [1,2,3]

In [11]:
type(a)

list

The difference between the `v` and `m` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [12]:
v.shape

(5,)

In [13]:
m.shape

(2, 3)

The number of elements in the array is available through the `ndarray.size` property

In [14]:
m.size

6

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [15]:
m.dtype

dtype('int32')

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [16]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

### Create Matrix Zeros

In [17]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [18]:
#two dimension

zeros_matrix2 = np.zeros(5,2)

TypeError: data type not understood

In [19]:
# should  be in tuple format

zeros_matrix2 = np.zeros(shape=(5,2)) # 5 rows, 2 columns
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Matrix ones

In [20]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [21]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [6]:
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

In [7]:
m1.shape

(4, 3)

2. Create the following matrix
![](image/lat11.png)

3. Create a 2D matrix with size of 10

4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

5. Make the following arrays from zeros arrays and with for loops
![](image/exercise1.png)

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

**arange**

In [11]:
# create a range

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [13]:
# create a range

x = np.arange(10, 20) # arguments: start, stop

x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
# create a range

x = np.arange(10, 20, 2) # arguments: start, stop, step

x

array([10, 12, 14, 16, 18])

In [24]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

The number 9.00000000e-01 already is a floating point number.
It's written in scientific notation and is equivalent to 9 * 10**-1 or 0.9.

#### linspace

In [25]:
# using linspace, both end points ARE included
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [26]:
np.linspace(1,10,4) 

array([ 1.,  4.,  7., 10.])

#### random data

In [27]:
from numpy import random

In [45]:
random.rand()

0.2703855533601057

In [40]:
#uniform random numbers in [0,1]
random.rand(5,5) 

array([[0.1852141 , 0.2029008 , 0.43468925, 0.39686479, 0.47550711],
       [0.58133582, 0.82894008, 0.10558235, 0.33947126, 0.85586809],
       [0.22788598, 0.49726488, 0.94579618, 0.08946392, 0.92249017],
       [0.43722633, 0.17626488, 0.22104434, 0.14452362, 0.61232868],
       [0.88260122, 0.57418102, 0.18201663, 0.96087907, 0.16673055]])

In [41]:
# standard normal distributed random numbers
x = random.randn(3,2)
x

array([[ 0.11964772, -0.79645559],
       [ 0.46171104, -1.10157497],
       [ 1.09352496, -0.48979759]])

In [31]:
x.dtype

dtype('float64')

In [32]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1], dtype=int64)

In [35]:
random.randint(10) #random int

3

In [37]:
random.randint(2, 10, size=4)

array([2, 4, 7, 9])

In [39]:
random.randint(2, 10, size=(4,2,2))

array([[[2, 7],
        [6, 8]],

       [[7, 7],
        [5, 6]],

       [[5, 8],
        [6, 5]],

       [[3, 7],
        [9, 4]]])

In [9]:
from numpy import random

In [12]:
random.randint(0, 100, size=5)

array([25, 88, 52, 18, 83])

In [15]:
random.randint(0,100, size=(3,5))

array([[15, 40, 34, 95, 78],
       [51, 79, 98,  2, 63],
       [56, 43, 33, 83, 59]])

In [21]:
np.linspace(1.5,5.5,30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
x = np.array([[0,1,3],[5,7,9]])
y = np.array([[0,2,4],[6,8,10]])


In [29]:
np.concatenate((x,y), axis=1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [31]:
arr = np.arange(2,11)
arr.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [32]:
x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
